version: "2.4"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  
  bild:
    build:
      context: .
      target: bild
    depends_on:
      - redis
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017
      REDIS_URL: redis:6379
      BILD_TOPICS: news,politik,unterhaltung,sport,lifestyle,ratgeber,auto,digital,spiele
  
  russiatoday:
    build:
      context: .
      target: russiatoday
    depends_on:
      - redis
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017
      REDIS_URL: redis:6379
  
  spiegel:
    build:
      context: .
      target: spiegel
    depends_on:
      - redis
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017
      REDIS_URL: redis:6379
      SPIEGEL_TOPICS: politik,wirtschaft,panorama,sport,kultur,netzwelt,wissenschaft,gesundheit,karriere,lebenundlernen,reise,auto